[tools]
go = "1.25"

# Python + uv (fast package/venv manager)
python = "3.12"
uv = "latest"

# Node.js (npm & npx included)
node = "24"

[env]
GOPATH = "{{ get_env(name='HOME', default=get_env(name='USERPROFILE', default='')) }}/go"
_.path = ["{{env.GOPATH}}/bin"]
